### ISSUE TITLE
MySQL tests are not reproducible

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-jdbc#109]
### Expected Behavior

MySQL tests should be reproducible on any environment.

### Actual Behaviour

On some env, MySQL tests fails with:

```
  io.kestra.plugin.jdbc.mysql.MysqlTest ✘ select() (1s)

    java.lang.AssertionError: 
    Expected: is <2050-12-31T22:59:57.150150Z>
         but: was <2050-12-31T21:59:57.150150Z>
```

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Linux loic-16Z90Q-G-AD78F 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 4 12:14:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Java Version (If not docker): openjdk version "17.0.5" 2022-10-18
