### ISSUE TITLE
Installing HTTPFS extension in a DuckDB query breaks the Kestra container

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#128]
### Expected Behavior

When running this flow, Kestra container breaks:

```yaml
id: duckDBqueryS3
namespace: prod
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello from Kestra!
  - id: duckDB
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      SELECT Title, max("Days In Top 10") 
      from (SELECT * FROM read_parquet('s3://duckdb-md-dataset-121/netflix_daily_top_10.parquet'))
      where Type='Movie'
      GROUP BY Title
      ORDER BY max("Days In Top 10") desc
      limit 5;
    fetch: true
```

This S3 file has only 7100 rows so data size is not the problem, it's likely due to the HTTPFS extensionthe 

### Environment Information

- Kestra Version: develop full
