### ISSUE TITLE
Postgres Void object are not serialized 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-jdbc#130]
```yaml
  - id: postgres
    type: io.kestra.plugin.jdbc.postgresql.Trigger
    interval: "PT5S"
    url: jdbc:postgresql://local:5432/kestra
    username: kestra
    password: k3str4
    fetch: true
    sql: "SELECT pg_sleep(15) as val"
```
lead to 
```
  - id: postgres
    type: io.kestra.plugin.jdbc.postgresql.Trigger
    interval: "PT5S"
    url: jdbc:postgresql://local:5432/kestra
    username: kestra
    password: k3str4
    fetch: true
    sql: "SELECT pg_sleep(15) as val"
```
should be simply null
