### ISSUE TITLE
ClickHouse Query task throws a data type error `Invalid Column Type 'DateTime'`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#136]
### Expected Behavior

Example to reproduce:

```yaml
id: queryClickHouse
namespace: dev
description: |
  This flow will create a database in ClickHouse if it does not already exist.
  docker run -d -p 8123:8123 -p 9000:9000 --name myclickhouse --ulimit nofile=262144:262144 clickhouse/clickhouse-server

tasks:
  - id: db
    type: io.kestra.plugin.jdbc.clickhouse.Query
    sql: CREATE DATABASE IF NOT EXISTS helloworld

  - id: tbl
    type: io.kestra.plugin.jdbc.clickhouse.Query
    sql: |
      CREATE TABLE IF NOT EXISTS helloworld.my_first_table
      (
          user_id String,
          message String,
          timestamp DateTime,
          metric Float32
      )
      ENGINE = MergeTree()
      PRIMARY KEY (user_id, timestamp)

  - id: data
    type: io.kestra.plugin.jdbc.clickhouse.Query
    sql: |
      INSERT INTO helloworld.my_first_table (user_id, message, timestamp, metric) VALUES
          (101, 'Hello, ClickHouse!',                                 now(),       -1.0    ),
          (102, 'Insert a lot of rows per batch',                     yesterday(), 1.41421 ),
          (102, 'Sort your data based on your commonly-used queries', today(),     2.718   ),
          (101, 'Granules are the smallest chunks of data read',      now() + 5,   3.14159 )

  - id: query
    type: io.kestra.plugin.jdbc.clickhouse.Query
    sql: SELECT * FROM helloworld.my_first_table
    fetch: true

taskDefaults:
  - type: io.kestra.plugin.jdbc.clickhouse.Query
    values:
      url: jdbc:clickhouse://host.docker.internal:8123/
      username: default
```

### Environment Information

- Kestra Version: develop full image
