### ISSUE TITLE
Snowflake query task cannot use tasks from internal storage: `File not found.`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#138]
### Issue description

MRE:

```yaml
id: snowflakeTutorial
namespace: dev

tasks:
  - id: createDB
    type: io.kestra.plugin.jdbc.snowflake.Query
    sql: CREATE OR REPLACE DATABASE KESTRA;

  - id: createTable
    type: io.kestra.plugin.jdbc.snowflake.Query
    sql: |
      CREATE OR REPLACE TABLE KESTRA.PUBLIC.EMPLOYEES (
        first_name STRING ,
        last_name STRING ,
        email STRING ,
        streetaddress STRING ,
        city STRING ,
        start_date DATE
        );

  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://raw.githubusercontent.com/kestra-io/examples/main/datasets/employees01.csv

  - id: load
    type: io.kestra.plugin.jdbc.snowflake.Query
    sql: put file://{{outputs.extract.uri}} @kestra.public.%employees

taskDefaults:
  - type: io.kestra.plugin.jdbc.snowflake.Query
    values:
      url: jdbc:snowflake://accountid.snowflakecomputing.com?warehouse=DEMO
      username: ANNA
      password: 'password'
```
