### ISSUE TITLE
Add MotherDuck support to the DuckDB plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#143]
### Feature description

MotherDuck should work out of the box based on the existing JDBC driver for DuckDB: https://motherduck.com/docs/integrations/jdbc-driver

![image](https://github.com/kestra-io/plugin-jdbc/assets/86264395/86d0b395-58e6-4942-a9e2-cabcd2430b4d)

But I can't connect, even when explicitly setting the token in the JDBC URL

```yaml
id: md
namespace: dev
tasks:
  - id: md
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      SELECT passenger_count, avg(total_amount) as avg_fare
      FROM sample_data.nyc.yellow_cab_nyc_2022_11
      GROUP BY passenger_count
      ORDER by passenger_count;
    store: true

taskDefaults:
  - type: io.kestra.plugin.jdbc.duckdb.Query
    values:
      url: "jdbc:duckdb:md:my_db"
      timeZoneId: Europe/Berlin
```

A dedicated plugin with the MotherDuck logo and an easier way to pass the MOTHERDUCK_TOKEN from a secret would be quite useful 

The JDBC driver from here works well in my local IDE with both DuckDB and MotherDuck https://central.sonatype.com/artifact/org.duckdb/duckdb_jdbc/0.8.1/versions
