### ISSUE TITLE
DuckDB query can break the Kestra container

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#145]
### Issue description

This flow will work fine:

```yaml
id: query
namespace: md

tasks:
  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      SELECT month(order_date) as month, sum(total) as total 
      FROM read_csv_auto('s3://kestraio/monthly_orders/*.csv', FILENAME = 1) 
      GROUP BY 1
      ORDER BY 2 desc;
    store: true
    timeout: PT20S
    url: "jdbc:duckdb:md:my_db?motherduck_token={{ secret('MOTHERDUCK_TOKEN') }}"

  - id: csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.query.uri }}"
```

Now try to access an S3 directory that doesn't exist:

```yaml
id: query
namespace: md

tasks:
  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      SELECT month(order_date) as month, sum(total) as total 
      FROM read_csv_auto('s3://kestraio/monthly_orders_2023/*.csv', FILENAME = 1) 
      GROUP BY 1
      ORDER BY 2 desc;
    store: true
    timeout: PT20S
    url: "jdbc:duckdb:md:my_db?motherduck_token={{ secret('MOTHERDUCK_TOKEN') }}"

  - id: csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.query.uri }}"
```

DuckDB normally would return IOError and exit:

![image](https://github.com/kestra-io/plugin-jdbc/assets/86264395/a513b8c5-7e05-49f4-81cc-e3609c443a1b)

However, this is what happens in Kestra container:
```
2023-07-24 11:38:09 2023-07-24 09:38:09,826 INFO  default-nioEventLoopGroup-1-5 io.kestra.webserver.access [Date: 2023-07-24T09:38:09.578668125Z] [Duration: 243 ms] [Method: POST] [Url: /api/v1/executions/trigger/md/query] [Status: 200] [Length: 295] [Ip: 172.21.0.1] [Port: 8080]
2023-07-24 11:38:09 2023-07-24 09:38:09,932 INFO  default-nioEventLoopGroup-1-5 io.kestra.webserver.access [Date: 2023-07-24T09:38:09.913291042Z] [Duration: 18 ms] [Method: GET] [Url: /api/v1/flows/md/query?source=true&id=query&namespace=md&deleted=true] [Status: 200] [Length: 477] [Ip: 172.21.0.1] [Port: 8080]
2023-07-24 11:38:10 2023-07-24 09:38:10,368 INFO  jdbc-queue_4 flow.query   [namespace: md] [flow: query] [execution: 3kxBrIkExFs9MZQMXSM2nU] Flow started
2023-07-24 11:38:14 2023-07-24 09:38:14,132 INFO  worker_329   flow.query.query [namespace: md] [flow: query] [task: query] [execution: 3kxBrIkExFs9MZQMXSM2nU] [taskrun: 1qObqqLYXFV5awn614sNcq] [value: null] Type Query started
2023-07-24 11:38:24 /bin/bash: line 1:     6 Aborted                 /app/kestra server standalone --worker-thread=128
```

can it be that IO errors are not handled properly?

**Comment by anna-geller** [comment]
when restarting the container, the execution is stuck in a Running state 

![image](https://github.com/kestra-io/plugin-jdbc/assets/86264395/7fcaaf46-bfd3-4b3e-8d44-733076feb1e9)

**Comment by anna-geller** [comment]
Sorry for a bad reproducer, here is one that should work directly, even without MotherDuck, you'd only need to replace AWS credentials and the bucket name variable:

this should work:
```yaml
id: s3Upload
namespace: md

variables:
  bucket: kestraio

tasks:
  - id: s3upload
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: ghcr.io/kestra-io/aws:latest
    env:
      AWS_ACCESS_KEY_ID: "{{ secret('AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
      AWS_DEFAULT_REGION: "{{ secret('AWS_DEFAULT_REGION') }}"
    script: |
      import requests
      import boto3
      from kestra import Kestra

      BUCKET = "{{vars.bucket}}"


      def extract_and_upload(file):
          url = f"https://raw.githubusercontent.com/kestra-io/datasets/main/{file}"

          response = requests.get(url)
          data = response.content.decode("utf-8")
          s3 = boto3.resource("s3")
          s3.Bucket(BUCKET).put_object(Key=file, Body=data)
          print(f"{url} downloaded and saved to {BUCKET}/{file}")


      for month in range(1, 13):
          filename = f"monthly_orders/2023_{str(month).zfill(2)}.csv"
          extract_and_upload(filename)
          Kestra.outputs({f"{filename}": f"s3://{BUCKET}/{filename}"})

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SET s3_region='{{ secret('AWS_DEFAULT_REGION') }}';
      SET s3_access_key_id='{{ secret('AWS_ACCESS_KEY_ID') }}';
      SET s3_secret_access_key='{{ secret('AWS_SECRET_ACCESS_KEY') }}';
      SELECT month(order_date) as month, sum(total) as total 
      FROM read_csv_auto('s3://{{vars.bucket}}/monthly_orders/*.csv', FILENAME = 1) 
      GROUP BY 1
      ORDER BY 2 desc;
    store: true
    timeout: PT30S

  - id: csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.query.uri }}"
```

Now changing the path in the DuckDB query from `monthly_orders` to `monthly_orders_2023` should break the container (at least it did for me back then)

but... now on the latest develop full it works as expected 😅 

![image](https://github.com/kestra-io/plugin-jdbc/assets/86264395/52dfc782-a5d1-4801-a21a-64d10382783f)

even when using remote DB with MotherDuck

```yaml
id: s3Upload
namespace: md

variables:
  bucket: kestraio

tasks:
  - id: s3upload
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: ghcr.io/kestra-io/aws:latest
    env:
      AWS_ACCESS_KEY_ID: "{{ secret('AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
      AWS_DEFAULT_REGION: "{{ secret('AWS_DEFAULT_REGION') }}"
    script: |
      import requests
      import boto3
      from kestra import Kestra

      BUCKET = "{{vars.bucket}}"


      def extract_and_upload(file):
          url = f"https://raw.githubusercontent.com/kestra-io/datasets/main/{file}"

          response = requests.get(url)
          data = response.content.decode("utf-8")
          s3 = boto3.resource("s3")
          s3.Bucket(BUCKET).put_object(Key=file, Body=data)
          print(f"{url} downloaded and saved to {BUCKET}/{file}")


      for month in range(1, 13):
          filename = f"monthly_orders/2023_{str(month).zfill(2)}.csv"
          extract_and_upload(filename)
          Kestra.outputs({f"{filename}": f"s3://{BUCKET}/{filename}"})

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      SELECT month(order_date) as month, sum(total) as total 
      FROM read_csv_auto('s3://{{vars.bucket}}/monthly_orders_2023/*.csv', FILENAME = 1) 
      GROUP BY 1
      ORDER BY 2 desc;
    store: true
    timeout: PT30S
    url: "jdbc:duckdb:md:my_db?motherduck_token={{ secret('MOTHERDUCK_TOKEN') }}"

  - id: csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.query.uri }}"
```

weird.

Closing the issue then for now, thanks for rubberducking @loicmathieu
