### ISSUE TITLE
Add support for JSON columns -- atm any Query gives the error `PGobject of type [jsonb] is not supported`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#235]
### Feature description

Atm, we can't query our own database 😢 

```yaml
id: hello-world
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: kestra
    sql: "SELECT * FROM flows"
    store: true
```
