### ISSUE TITLE
DuckDB Plugin cannot use a DB file from the current WorkingDirectory

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#268]
### Feature description

Use case: you ingest or transform data with DuckDB in one task and you want to use it in a downstream task within children tasks of `WorkingDirectory`:
- ✅ Doing it in Python works
- ❌ Doing it in kestra DuckDB plugin doesn't work

See the example below where the Python task just works and the DuckDB plugin fails:

```yaml
id: dbt_duckdb
namespace: blueprint

variables:
  db: "dbt.duckdb"

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      outputFiles:
        - db.duckdb
      runner: DOCKER
      docker:
        image: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps
        - dbt build
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: "{{ vars.db }}"
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev

    - id: python
      type: io.kestra.plugin.scripts.python.Script
      outputFiles:
        - "*.csv"
      docker:
        image: ghcr.io/kestra-io/duckdb:latest
      script: |
        import duckdb
        import pandas as pd

        conn = duckdb.connect(database="{{ vars.db }}")

        tables_query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';"
        tables = conn.execute(tables_query).fetchall()

        # Export each table to CSV, excluding tables that start with 'raw' or 'stg'
        for table_name in tables:
            table_name = table_name[0]
            # Skip tables with names starting with 'raw' or 'stg'
            if not table_name.startswith('raw') and not table_name.startswith('stg'):
                query = f"SELECT * FROM {table_name}"
                df = conn.execute(query).fetchdf()
                df.to_csv(f"{table_name}.csv", index=False)

        conn.close()

    - id: query
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: jdbc:duckdb:dbt.duckdb
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true
      allowFailure: true

    - id: query1
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: "jdbc:duckdb:{{ vars.db }}"
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true
      allowFailure: true

    - id: query2
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: jdbc:duckdb:{{workingDir}}/dbt.duckdb
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true      
      allowFailure: true
      
    - id: query3
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: jdbc:duckdb:./dbt.duckdb
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true      
      allowFailure: true      
```
