### ISSUE TITLE
The {{ workingDir }} is not rendered correctly in DuckDB Query task when the query is passed from a SQL file stored as a namespace file

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#300]
### Expected Behavior

Ideally, the `{{ workingDir }}` should not be needed. Given that the file is passed as part of `inputFiles`, you shouldn't need that workingDir part here:

```sql
INSTALL json;
LOAD json;
SELECT brand, round(avg(price), 2) as avg_price
FROM read_json_auto('{{ workingDir }}/products.json')
GROUP BY brand
ORDER BY avg_price DESC;
```

![image](https://github.com/kestra-io/plugin-jdbc/assets/86264395/ad9454cf-c749-46da-995a-9122f5cef537)

reproducer:

```yaml
id: myflow
namespace: myteam

inputs:
  - id: columns_to_keep
    type: STRING
    defaults: |-
      ["brand", "price"]

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products

  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-alpine
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json"
    env:
      COLUMNS_TO_KEEP: "{{ inputs.columns_to_keep }}"
    namespaceFiles:
      enabled: true
    script: |
      import json
      import os

      with open("data.json", "r") as file:
          data = json.load(file)

      filtered_data = [
          {column: product.get(column, "N/A") for column in {{ inputs.columns_to_keep }}}
          for product in data["products"]
      ]

      with open("products.json", "w") as file:
          json.dump(filtered_data, file, indent=4)    

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      products.json: "{{ outputs.transform.outputFiles['products.json'] }}"
    sql: |
      INSTALL json;
      LOAD json;
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_json_auto('{{ workingDir }}/products.json')
      GROUP BY brand
      ORDER BY avg_price DESC;
    store: true

  - id: query_fail
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      products.json: "{{ outputs.transform.outputFiles['products.json'] }}"
    sql: "{{ read('query.sql')}}"
    store: true
```

you'll need to add `query.sql` as a namespace file with this content:
```sql
INSTALL json;
LOAD json;
SELECT brand, round(avg(price), 2) as avg_price
FROM read_json_auto('{{ workingDir }}/products.json')
GROUP BY brand
ORDER BY avg_price DESC;
```
