### ISSUE TITLE
Add a new Queries task to run multiple SQL with multiple outputs, parameter binding and transactions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#368]
### **Context**

The current `Query` task is limited to executing a single SQL statement and handling its output. Some automation tasks require executing multiple SQL statements, potentially wrapped in a transaction, while handling outputs of multiple `SELECT` statements. 

To avoid breaking changes in the `Query` tasks, here is a proposal for a new `Queries` task.

This task will enable:
- execution of multiple SQL statements
- managing outputs of multiple SELECT queries
- handling parameters to prevent SQL injection
- transactions.

### Use case for testing

Start Postgres in a container:

```sql
docker run --name queries -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_USER=postgres -e POSTGRES_DB=postgres -p 5432:5432 -d postgres
```

Create tables (alternatively directly from the new task):

```sql
CREATE TABLE myusers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    last_login TIMESTAMP
);

CREATE TABLE mylogs (
    log_id SERIAL PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    FOREIGN KEY (user_email) REFERENCES myusers(email)
);
```

### **Implementation**

**Task Type**: `io.kestra.plugin.jdbc.postgresql.Queries` (equivalent tasks will be needed for all JDBC plugin subgroups, not just Postgres)

**Description**: The `Queries` task allows executing multiple SQL statements within a single task, with support for parameter binding and transaction management. The task can handle multiple `SELECT` statements and their outputs, allowing you to fetch the results directly or store them as internal storage ION files.

### **Properties**

- **sql**:
    - **Type**: `string`
    - **Required**: ✔️
    - **Description**: A single string containing multiple SQL statements separated by semicolons `;`. The statements will be executed sequentially (optionally as part of a transaction).
- **parameters**:
    - **Type**: `map`
    - **Required**: ❌
    - **Description**: A map of parameters to bind to the SQL queries. The keys should match the parameter placeholders in the SQL string, e.g., `:parameterName`.
- **transaction**:
    - **Type**: `boolean`
    - **Required**: ❌
    - **Default**: `false`
    - **Description**: If `true`, all SQL statements will be executed within a single transaction. The transaction will commit if all statements succeed; otherwise, it will roll back. If `false`, the task will auto-commit each SQL statement independently. 
- **fetch**:
    - **Type**: `boolean`
    - **Required**: ❌
    - **Default**: `false`
    - **Description**: When `true`, the task fetches the results of all `SELECT` statements and makes them available in the task output as a map.
- **fetchOne**:
    - **Type**: `boolean`
    - **Required**: ❌
    - **Default**: `false`
    - **Description**: When `true`, only the first row of each `SELECT` statement's result is fetched and stored in the task output.
- **store**:
    - **Type**: `boolean`
    - **Required**: ❌
    - **Default**: `true`
    - **Description**: When `true`, results from `SELECT` statements are stored as ION-formatted files in internal storage. The output will be a map of URIs, with the keys being the query identifiers e.g. `{query_1: URI, query_2: URI}`.

### **Outputs**

- data (if `fetch: true` or `fetchOne: true`):
    - **Type**: `map`
    - **SubType**: `array` or `object` (depending on `fetch` or `fetchOne`)
    - **Description**: A map where each key corresponds to the SQL query index (e.g., `query_1`, `query_2`, etc.), and the value is the result set (an array of rows) or the first row if `fetchOne` is true.
- **uris** (if `store: true`):
    - **Type**: `map`
    - **SubType**: `string` (URI)
    - **Description**: A map where each key corresponds to the SQL query index (e.g., `query_1`, `query_2`, etc.), and the value is the URI of the stored file for that query's result.
- **rowCounts**:
    - **Type**: `array`
    - **SubType**: `integer`
    - **Description**: An array representing the number of rows affected by each SQL statement executed (e.g., `INSERT`, `UPDATE`, `DELETE`). For `SELECT` statements, the value is `0`.
- **transactionStatus**:
    - **Type**: `string`
    - **Description**: The status of the transaction, either `committed` or `rolled back`, based on the query execution outcome when `transaction` is `true`.

### **Example flow**

```yaml
id: run_queries
namespace: company.team

tasks:
  - id: setup
    type: io.kestra.plugin.jdbc.postgresql.Queries
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: xxx
    sql: |
      DROP TABLE IF EXISTS myusers CASCADE;
      CREATE TABLE myusers (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        last_login TIMESTAMP
      );
      DROP TABLE IF EXISTS mylogs;
      CREATE TABLE mylogs (
              log_id SERIAL PRIMARY KEY,
              user_email VARCHAR(255) NOT NULL,
              action VARCHAR(255) NOT NULL,
              timestamp TIMESTAMP NOT NULL,
              FOREIGN KEY (user_email) REFERENCES myusers(email)
      );

  - id: queries
    type: io.kestra.plugin.jdbc.postgresql.Queries
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: xxx
    sql: |
      INSERT INTO myusers (name, email) VALUES (:name, :email) ON CONFLICT (email) DO NOTHING;
      UPDATE myusers SET last_login = :login WHERE email = :email;
      INSERT INTO mylogs (user_email, action, timestamp) VALUES (:email, 'login', :login);
      SELECT * FROM myusers WHERE email = :email;
      SELECT * FROM mylogs WHERE user_email = :email;
    parameters:
      name: Rick
      email: "rick@kestra.io"
      login: "{{ execution.startDate }}"
    transaction: true
    fetch: true
    store: false
```

### **Example output**

Fetch multiple rows (`fetch: true`, `store: false`):

```json
{
  "data": {
    "query_4": [
      {
        "id": 1,
        "name": "Rick",
        "email": "rick@kestra.io",
        "last_login": "2024-08-29T10:00:00Z"
      }
    ],
    "query_5": [
      {
        "log_id": 1,
        "user_email": "rick@kestra.io",
        "action": "login",
        "timestamp": "2024-08-29T10:00:00Z"
      }
    ]
  },
  "rowCounts": [1, 1, 1, 0, 0],
  "transactionStatus": "committed"
}

```

Store results (`store: true`, `fetch: false`) --> default option:

```json
{
  "uris": {
    "query_4": "kestra:///internal/storage/queries-result-3.ion",
    "query_5": "kestra:///internal/storage/queries-result-4.ion"
  },
  "rowCounts": [1, 1, 1, 0, 0],
  "transactionStatus": "committed"
}
```

Fetch one row from each `SELECT` (`fetchOne: true`, `store: false`):

```json
{
  "data": {
    "query_4": {
      "id": 1,
      "name": "Rick",
      "email": "rick@kestra.io",
      "last_login": "2024-08-29T10:00:00Z"
    },
    "query_5": {
      "log_id": 1,
      "user_email": "rick@kestra.io",
      "action": "login",
      "timestamp": "2024-08-29T10:00:00Z"
    }
  },
  "rowCounts": [1, 1, 1, 0, 0],
  "transactionStatus": "committed"
}
```
