### ISSUE TITLE
Support for Oracle correct mapping of Oracle NUMBER types (e.g., NUMBER(9,0) as Int and NUMBER(5,2) as Double)

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-jdbc#385]

**Comment by Ben8t** [comment]
@tchiotludo can you provide a bit more details over this one 🤔 ?

Is it about properly mapping Kestra `INT` to `NUMBER(9,0)` and `FLOAT` to `NUMBER(5,2)` when using Kestra values inside SQL Oracle query ?

**Comment by tchiotludo** [comment]
No idea, just a fire and forget from a prospect.
The goal is to dig into that NUMBER to see if we have any issues

**Comment by Ben8t** [comment]
```yaml
id: fox_291116
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: oracle
    type: io.kestra.plugin.jdbc.oracle.Query
    url: jdbc:oracle:thin:@host.docker.internal:1521
    username: SYSTEM
    password: 123Soleil!
    sql: |
      CREATE TABLE IF NOT EXISTS NUMBER_TYPE_TEST (
        INT_COLUMN NUMBER(9,0),
        DOUBLE_COLUMN NUMBER(5,2)
      )
    fetchType: STORE

  - id: oracle2
    type: io.kestra.plugin.jdbc.oracle.Query
    url: jdbc:oracle:thin:@host.docker.internal:1521
    username: SYSTEM
    password: 123Soleil!
    sql: |
      INSERT INTO NUMBER_TYPE_TEST (INT_COLUMN, DOUBLE_COLUMN) VALUES (123456789, 123.45)
    fetchType: STORE

  - id: oracle3
    type: io.kestra.plugin.jdbc.oracle.Query
    url: jdbc:oracle:thin:@host.docker.internal:1521
    username: SYSTEM
    password: 123Soleil!
    sql: |
      SELECT * FROM NUMBER_TYPE_TEST 
    fetchType: FETCH
```

![Image](https://github.com/user-attachments/assets/ed3d5ffc-58e9-4b5a-a517-a0886726410f)

![Image](https://github.com/user-attachments/assets/8a36ff62-580e-4afc-89a3-67540aa76ac2)

I'm closing this issue as it seems to be supported
