### ISSUE TITLE
Can't query using MotherDuck connection

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-jdbc#395]
### Expected Behavior

Following the documentation and blueprint, the MotherDuck doesn't seem to work anymore.

![image](https://github.com/user-attachments/assets/468fb6e9-9c03-4d99-9a19-a1d3ff76c62b)

access to MotherDuck https://app.motherduck.com/

```yaml
id: myflow
namespace: company.team

tasks:
  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    url: "jdbc:duckdb:md:test?motherduck_token=<TOKEN>"
    sql: |
      SELECT by, COUNT(*) as nr_comments 
      FROM sample_data.hn.hacker_news
      GROUP BY by
      ORDER BY nr_comments DESC;
    store: true
```

### Environment Information

- Kestra Version: 0.19.2
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
