### ISSUE TITLE
Duckdb dynamic database

### ISSUE THREAD

**Issue by Vinceveve** [kestra-io/plugin-jdbc#448]
### Describe the issue

I have an issue with duckdb  if i use the sample from [the doc](https://kestra.io/plugins/plugin-jdbc-duckdb/tasks/io.kestra.plugin.jdbc.duckdb.query) I get and error `>io.kestra.plugin.jdbc.duckdb.Query["databaseFile"]: Unrecognized field "databaseFile"`

If I use a variable (or input) on the url, I get `The database file path is not valid (Path to database file must be absolute)`

Example task : 
```
variables: 
  db: /temp/occ/rodez/set_parent_station.db
tasks: 
  - id: create_stop_table
    type: io.kestra.plugin.jdbc.duckdb.Query
    url: "jdbc:duckdb:{{ vars.db }}"
```

![image](https://github.com/user-attachments/assets/1a0d63dd-ea5d-4ec4-b8a4-f70ac40972f4)

### Environment

- Kestra Version: 0.19.10

**Comment by Ben8t** [comment]
Indeed there's something wrong in the documentation about the `databaseFile`, as it's not a [proper property](https://github.com/kestra-io/plugin-jdbc/blob/0a6795b4bface9857ce23f312b6421d9d316788e/plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java#L141).

FYI in the meantime, we have recently fixed an old DuckDB issue: now Kestra use the latest version 1.1.3. The following flow works:

```yaml
id: duckdb_fil
namespace: kestra.test

tasks:  

  - id: db
    type: io.kestra.plugin.jdbc.duckdb.Queries
    url: jdbc:duckdb:/test_db/data.db  # this file is mounted on my local computer
    sql: |
      CREATE TABLE IF NOT EXISTS t1 (i INTEGER, j INTEGER);
      INSERT INTO t1 VALUES (1, 2);
      SELECT * FROM t1;
    store: true


  - id: db2
    type: io.kestra.plugin.jdbc.duckdb.Query
    url: jdbc:duckdb:/test_db/data.db
    sql: |
      SELECT * FROM t1;
    store: true
```

@mgabelle can you check why the `databaseFile` prop isn't accessible from a user pov ? Can you ping me when you have an idea please? We might want to reevulate the overlap between using `url: jdbc:duckdb:/test_db/data.db` and the `databaseFile` (which seems the same to me 🤔 )
