### ISSUE TITLE
DuckDB doesn't work with Java Security enabled — ExceptionInInitializerError

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-jdbc#456]
### Describe the issue

```
"Caught an exception in Thread[#395,worker_9,5,main]. Shutting down.\njava.lang.ExceptionInInitializerError: null
org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:46)
org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:38)\n\tat java.sql/java.sql.DriverManager.getConnection(Unknown Source)
 java.sql/java.sql.DriverManager.getConnection(Unknown Source)
io.kestra.plugin.jdbc.JdbcConnectionInterface.connection(JdbcConnectionInterface.java:68)
io.kestra.plugin.jdbc.AbstractJdbcQuery.run(AbstractJdbcQuery.java:36)
io.kestra.plugin.jdbc.duckdb.Query.run(Query.java:235)
io.kestra.plugin.jdbc.duckdb.Query.run(Query.java:32)
io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78)
io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:56)
io.kestra.ee.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:20)
io.kestra.core.runners.Worker.callJob(Worker.java:772)
io.kestra.core.runners.Worker.runAttempt(Worker.java:731)
io.kestra.core.runners.Worker.run(Worker.java:582)
io.kestra.core.runners.Worker.handleTask(Worker.java:287
 io.kestra.core.runners.Worker.lambda$run$7(Worker.java:243)
io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.SecurityException: Unable to create temporary file or directory\n\tat java.base/java.nio.file.TempFileHelper.create(Unknown Source)
java.base/java.nio.file.TempFileHelper.createTempFile(Unknown Source)
java.base/java.nio.file.Files.createTempFile(Unknown Source)
 org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:45)\n\t... 20 common frames omitted\n","context":"default"
```

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
noticed the same today - bumping to P0

Reproducer:

```yaml
id: ion_to_parquet
namespace: company.team

tasks:
  - id: download_csv
    type: io.kestra.plugin.core.http.Download
    description: salaries of data professionals from 2020 to 2023 (source ai-jobs.net)
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/salaries.csv

  - id: avg_salary_by_job_title
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      data.csv: "{{ outputs.download_csv.uri }}"
    sql: |
      SELECT
        job_title,
        ROUND(AVG(salary),2) AS avg_salary
      FROM read_csv_auto('{{ workingDir }}/data.csv', header=True)
      GROUP BY job_title
      HAVING COUNT(job_title) > 10
      ORDER BY avg_salary DESC;
    store: true

  - id: result
    type: io.kestra.plugin.serdes.parquet.IonToParquet
    from: "{{ outputs.avg_salary_by_job_title.uri }}"
    schema: |
      {
        "type": "record",
        "name": "Salary",
        "namespace": "com.example.salary",
        "fields": [
          {"name": "job_title", "type": "string"},
          {"name": "avg_salary", "type": "double"}
        ]
      }
```

![image](https://github.com/user-attachments/assets/f6af16da-11bd-4221-bef0-1261deb78f50)
