### ISSUE TITLE
SQL Server outputs wrong format

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-jdbc#490]
### Describe the issue

A user has created flow like this
```
tasks:
    - id: getParams
      type: io.kestra.plugin.jdbc.sqlserver.Queries
      url: jdbc:sqlserver://{{ secret(inputs.serverName ~ "_DEV_ADDRESS") }};trustServerCertificate=true
      username: ---
      password: ---
      sql: |
        DECLARE @DateFrom DATE = GETDATE ()-1
          , @DateTo DATE = GETDATE()-1
        EXEC [DataBase].[dbo].[sp] @DateFrom = @DateFrom, @DateTo = @DateTo;
      fetchType: STORE

    - id: resultToCSV
      type: io.kestra.plugin.serdes.csv.IonToCsv
      from: "{{ outputs.getParams.uri }}"
```

However, Kestra complains that `{{ outputs.getParams.uri }}` cannot be found. Instead looking at in-app docs, it expects `{{outputs.getParams.outputs.uri }}` which is inconsistent with online docs (and potential breaking change)

### Environment

- Kestra Version: latest (0.20)
