### ISSUE TITLE
Oracle performance issue with CLOB/NCLOB type

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-jdbc#528]
### Describe the issue

When ingesting data from another source, if the source data is text over 4000 characters, there is a significant performance penalty when inserting to the CLOB/NCLOB type in Oracle. 

https://docs.oracle.com/javadb/10.10.1.2/ref/rrefclob.html

By changing data type to NVARCHAR2(4000) for example the user sees good performance, but this is not sufficient as they need over 4000 characters

Possible cause:
https://github.com/kestra-io/plugin-jdbc/blob/a8e0698b4c556e4d9409dabc5dd9016d26f46a50/plugin-jdbc-oracle/src/main/java/io/kestra/plugin/jdbc/oracle/OracleCellConverter.java#L43

### Environment

- Kestra Version: 0.21.3

**Comment by paulgrainger85** [comment]
tl;dr - executing same insert via Kestra and a python script on the same machine
inserting to CLOB in Kestra takes 2 minutes
inserting to CLOB in python script takes 4 seconds

varchar insert in both cases is fine, 2-3 seconds

```
id: oracle_perf_test
namespace: company.team

pluginDefaults:
  - forced: false
    type: io.kestra.plugin.jdbc.oracle
    values:
      url: jdbc:oracle:thin:@(description=..)
      username: ADMIN
      password: ...

tasks:
  - id: create_clob_table
    type: io.kestra.plugin.jdbc.oracle.Query
    disabled: true
    fetchType: FETCH
    sql: |
      CREATE TABLE my_clob_table (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      my_clob_column CLOB
      )
  - id: create_varchar_table
    type: io.kestra.plugin.jdbc.oracle.Query
    fetchType: FETCH
    disabled: true
    sql: |
      CREATE TABLE no_clob_table (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vchar_col VARCHAR2(4000)
      )      
  - id: clear_clob
    type: io.kestra.plugin.jdbc.oracle.Query
    fetchType: FETCH
    sql: |
      delete from my_clob_table      

  - id: clear_vchar
    type: io.kestra.plugin.jdbc.oracle.Query
    fetchType: FETCH
    sql: |
      delete from no_clob_table      

  - id: create_data
    type: io.kestra.plugin.scripts.python.Script
    outputFiles:
      - row.json
    beforeCommands:
      - pip install kestra
    script: |
      from kestra import Kestra
      import amazon.ion.simpleion as ion
      import random, string, json

      with open("row.json", "w", encoding="utf-8") as f:
        for i in range(2500):
          random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
          json_obj = {"my_clob_column": random_string}
          f.write(json.dumps(json_obj) + "\n")

  - id: insert_clob
    type: io.kestra.plugin.jdbc.oracle.Batch
    from: "{{ outputs.create_data['outputFiles']['row.json'] }}"
    chunk: 2500
    sql: insert into my_clob_table(my_clob_column) values (?)

  - id: insert_varchar
    type: io.kestra.plugin.jdbc.oracle.Batch
    from: "{{ outputs.create_data['outputFiles']['row.json'] }}"
    sql: insert into no_clob_table(vchar_col) values (?)
```
GAANT

![Image](https://github.com/user-attachments/assets/5aa6a71d-8b2e-49e3-b3b0-40a9a2a7f158)


Similar python script
`pip install oracledb`

```
import oracledb, random, string
from datetime import datetime as dt

dsn = "(description= ...)"

connection = oracledb.connect(user="ADMIN", password="...", dsn=dsn, 
                              ssl_server_dn_match=True)
print("Connected successfully!")

# Establish connection using the DSN

cursor = connection.cursor()

# Define an INSERT statement
insert_query = """
    INSERT INTO no_clob_table (vchar_col) 
    VALUES (:1)
"""

insert_query_clob = """
    INSERT INTO my_clob_table (my_clob_column) 
    VALUES (:1)
"""


data = [( ''.join(random.choices(string.ascii_letters + string.digits, k=4000)), ) for _ in range(5000)]

print(f"{dt.now()} - starting execution of vchar insert")
# Execute the insert statement with multiple records
cursor.executemany(insert_query, data)
# Commit changes
connection.commit()
print(f"{dt.now()} - Data inserted successfully!")

print(f"{dt.now()} - starting execution of clob insert")
# Execute the insert statement with multiple records
cursor.executemany(insert_query_clob, data)
# Commit changes
connection.commit()
print(f"{dt.now()} - Data inserted successfully!")
```

output
```
Connected successfully!
2025-02-27 09:53:45.890216 - starting execution of vchar insert
2025-02-27 09:53:47.473978 - Data inserted successfully!
2025-02-27 09:53:47.474096 - starting execution of clob insert
2025-02-27 09:53:51.594279 - Data inserted successfully!
```
