### ISSUE TITLE
The inputFiles path on DuckDB should be a relative, not an absolute path (we shouldn't include the `/tmp/taskDir/`)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#585]
### Describe the issue

Reproducer:

```yaml
id: repro_duckdb
namespace: company.team

tasks:
  - id: get_zip_file
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/zip/2023-01.zip

  - id: unzip
    type: io.kestra.plugin.compress.ArchiveDecompress
    algorithm: ZIP
    from: "{{outputs.get_zip_file.uri}}"

  - id: duckdb
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles: "{{outputs.unzip.files}}"
    sql: SELECT * FROM read_csv_auto('**/*-outcomes.csv', union_by_name=true, filename=true);
    store: true
    # outputDbFile: true
```

The expected output is to have the 

![image](https://github.com/user-attachments/assets/23a33e67-2a7d-46c4-b2d3-af7aa1c420d9)

### Environment

- Kestra Version: develop
