### ISSUE TITLE
Kesta does rollback with fetchType: STORE

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/plugin-jdbc#605]
### Describe the issue

```
CREATE TABLE dbo.test (id int)
GO

CREATE PROCEDURE dbo.testProc 
AS 
BEGIN
SET NOCOUNT ON
INSERT INTO dbo.test
VALUES (1)

SELECT id
FROM dbo.test
END
```

kestra flow to reproduce - first task returns 1 row, second - 0, but should also 1, because we did insert in stored procedure
```

 - id: checkAndRecalculateDataOnSQL
    type: "io.kestra.plugin.jdbc.sqlserver.Query"
    url: 
    username: 
    password: 
    sql: EXEC [dbo].[testProc]
    fetchType: STORE

  - id: checkAndRecalculateDataOnSQL2
    type: "io.kestra.plugin.jdbc.sqlserver.Query"
    url: 
    username: 
    password: 
    sql: SELECT * FROM [dbo].[test]
    fetchType: FETCH  
```

![Image](https://github.com/user-attachments/assets/8fdfc3bd-fdec-407e-bae2-4d95e78b1895)

![Image](https://github.com/user-attachments/assets/110514bf-b03a-43d2-9345-ef331c68e14f)

### Environment

- Kestra Version: 0.22.2
